# Generated by Django 3.0.5 on 2020-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('version', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe')], max_length=20)),
                ('desc', models.CharField(max_length=500, verbose_name='desc')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('nationality', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('desc', models.CharField(max_length=500, verbose_name='desc')),
            ],
        ),
    ]
